/**
* @file BHXabslEngineExecutor.h
*
* Implementation of class BHXabslEngineExecutor.
*
* @author Martin Lötzsch
*/

#pragma once

#include "Platform/SystemCall.h"
#include "Tools/Xabsl/XabslEngine/XabslEngine.h"
#include "Tools/Streams/InStreams.h"
//#include "Tools/MessageQueue/InMessage.h"
//#include "Tools/MessageQueue/OutMessage.h"


/** Implements xabsl::ErrorHandler using the OUTPUT macro */
class BHXabslErrorHandler : public xabsl::ErrorHandler
{
public:
  /**
  * Constructor
  * @param id The id of the xabsl::Engine.
  */
  BHXabslErrorHandler(const char* id);

  /**
  * Prints out an error
  * @param text The text to display
  */
  virtual void printError(const char* text);

  /**
  * Prints out a message
  * @param text The text to display
  */
  virtual void printMessage(const char* text);

private:
  /** The id of the xabsl::Engine. */
  const char* id;
};

/** Implements xabsl::InputSource using the InConfigFile class */
class XabslFileInputSource : public xabsl::InputSource, public xabsl::NamedItem
{
public:
  /**
  * Constructor. Does not open the file
  * @param fileName The file name to open
  */
  XabslFileInputSource(const char* fileName);

  /** Destructor */
  ~XabslFileInputSource();

  /** opens the source that contains the intermediate code */
  virtual bool open();

  /** closes the source */
  virtual void close();

  /** reads a numeric value from the input source */
  virtual float readValue();

  /**
  * reads a string from the input source
  * @param destination The position where to write the string
  * @param maxLength the maximum length of the string
  * @return if the read succeded
  */
  virtual bool readString(char* destination, int maxLength);

private:
  /** The file to read the data from */
  InConfigFile* file;
};

/** Implements xabsl::InputSource using the InConfigMessage class */
class XabslMessageInputSource : public xabsl::InputSource
{
public:
  /**
  * Constructor. Does not open the file
  * @param message A reference to the message that contains the intermediate code
  */
  XabslMessageInputSource(/*InConfigMessage& message*/);

  /** Destructor */
  ~XabslMessageInputSource() {};

  /** opens the source that contains the intermediate code */
  virtual bool open() {return true;};

  /** closes the source */
  virtual void close() {};

  /** reads a numeric value from the input source */
  virtual float readValue();

  /**
  * reads a string from the input source
  * @param destination The position where to write the string
  * @param maxLength the maximum length of the string
  * @return if the read succeded
  */
  virtual bool readString(char* destination, int maxLength);

private:
  /** The file to read the data from */
  //InConfigMessage& message;
};

/**
* @class BHXabslEngineExecutor
*
* Executes an xabsl::Engine in the GT - architecture
*
* @author Martin Lötzsch
*/
class BHXabslEngineExecutor
{
public:
  /**
  * Constructor.
  * @param id The id of the xabsl::Engine derivate.
  * @param time A reference to a variable that contains the current time in ms.
  */
  BHXabslEngineExecutor(const char* id, const unsigned int& time);

  /** destructor */
  ~BHXabslEngineExecutor();

  /**
  * Creates a new engine
  */
  void init();

  /**
  * Creates a new engine
  * @param input An input source to read to intermediate code from
  */
  void init(xabsl::InputSource& input);

  /** Executes the engine */
  void executeEngine();

  /** Registers symbols and basic behaviors at the engine */
  virtual void registerSymbolsAndBasicBehaviors() = 0;

  /** Sets the selected Agent. If the last selected agent was different from
  * the new one, the root option is changed depending on the new agent.
  * @param name The name of the agent
  * @return if the agent was set
  */
  bool setSelectedAgent(const char* name);

  /**
  * Is called for every incoming debug message.
  * @param message An interface to read the message from the queue
  * @return if the messag was read
  */
 //bool handleXabslMessage(InMessage& message);

protected:
  /** An engine that executes the XABSL formalized behaviors */
  xabsl::Engine* pEngine;

  /** Is invoked when errors occur */
  BHXabslErrorHandler errorHandler;

  /** Is called if the engine could not be created */
  virtual void executeIfEngineCouldNotBeCreated() = 0;

  /**
  * Prints the main action that was generated by the execution of the engine to a string
  * @param buf the string where to print the action
  */
  virtual void printGeneratedMainActionToString(char* buf) const = 0;

private:
  /** The id of the xabsl::Engine derivate. */
  const char* id;


  /** A reference to the current system time */
  const unsigned int& time;

  /** Points to the only instance of this class in this process or is 0 if there is none. */
 // PROCESS_WIDE_STORAGE_STATIC(BHXabslEngineExecutor) theInstance;

  /** Function for XabslEngine */
  unsigned int getCurrentSystemTime() {return this->time;}

  //!@name Debug interface to the Xabsl Dialog
  //!@{
protected:
  /** Sends a debug message to the Xabsl dialog depending on the last request */
  //void sendDebugMessage(OutMessage& outMessage) const;

  /** Sends a debug message to the Xabsl dialog containing names of agents, options, basic behaviors, and symbols*/
  //void sendDebugSymbols(OutMessage& outMessage) const;

private:
  void sendActiveOptionsToStream(Out& out) const;

  /** The decimal input symbols that are watched by the Xabsl Dialog */
  xabsl::NamedArray<const xabsl::DecimalInputSymbol*> watchedDecimalInputSymbols;

  /** The boolean input symbols that are watched by the Xabsl Dialog */
  xabsl::NamedArray<const xabsl::BooleanInputSymbol*> watchedBooleanInputSymbols;

  /** The enumerated input symbols that are watched by the Xabsl Dialog */
  xabsl::NamedArray<const xabsl::EnumeratedInputSymbol*> watchedEnumeratedInputSymbols;

  /** The decimal output symbols that are watched by the Xabsl Dialog */
  xabsl::NamedArray<const xabsl::DecimalOutputSymbol*> watchedDecimalOutputSymbols;

  /** The boolean output symbols that are watched by the Xabsl Dialog */
  xabsl::NamedArray<const xabsl::BooleanOutputSymbol*> watchedBooleanOutputSymbols;

  /** The enumerated output symbols that are watched by the Xabsl Dialog */
  xabsl::NamedArray<const xabsl::EnumeratedOutputSymbol*> watchedEnumeratedOutputSymbols;

  /** The decimal output symbols that are set from the Xabsl Dialog */
  xabsl::NamedArray<xabsl::DecimalOutputSymbol*> setDecimalOutputSymbols;

  /** The values for the set decimal output symbols */
  xabsl::NamedArray<float> setDecimalOutputSymbolValues;

  /** The boolean output symbols that are set from the Xabsl Dialog */
  xabsl::NamedArray<xabsl::BooleanOutputSymbol*> setBooleanOutputSymbols;

  /** The values for the set boolean output symbols */
  xabsl::NamedArray<bool> setBooleanOutputSymbolValues;

  /** The output symbols that are set from the Xabsl Dialog */
  xabsl::NamedArray<xabsl::EnumeratedOutputSymbol*> setEnumeratedOutputSymbols;

  /** The values for the set output symbols */
  xabsl::NamedArray<int> setEnumeratedOutputSymbolValues;

  //!@}
};
