"""autogenerated by genpy from bh_motion/JointData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class JointData(genpy.Message):
  _md5sum = "92236a40d86b52629d6d8c305aa5f4d0"
  _type = "bh_motion/JointData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8[22] angles #numOfJoints
uint32 timeStamp
float32 cycleTime

"""
  __slots__ = ['angles','timeStamp','cycleTime']
  _slot_types = ['uint8[22]','uint32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       angles,timeStamp,cycleTime

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(JointData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.angles is None:
        self.angles = chr(0)*22
      if self.timeStamp is None:
        self.timeStamp = 0
      if self.cycleTime is None:
        self.cycleTime = 0.
    else:
      self.angles = chr(0)*22
      self.timeStamp = 0
      self.cycleTime = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.angles
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_struct_22B.pack(*_x))
      else:
        buff.write(_struct_22s.pack(_x))
      _x = self
      buff.write(_struct_If.pack(_x.timeStamp, _x.cycleTime))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 22
      self.angles = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.timeStamp, _x.cycleTime,) = _struct_If.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.angles
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_struct_22B.pack(*_x))
      else:
        buff.write(_struct_22s.pack(_x))
      _x = self
      buff.write(_struct_If.pack(_x.timeStamp, _x.cycleTime))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 22
      self.angles = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.timeStamp, _x.cycleTime,) = _struct_If.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_22s = struct.Struct("<22s")
_struct_22B = struct.Struct("<22B")
_struct_If = struct.Struct("<If")
