"""autogenerated by genpy from bh_motion/MotionInfo.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import bh_motion.msg

class MotionInfo(genpy.Message):
  _md5sum = "3701d4d543b3d5fec0b6175a48353ff7"
  _type = "bh_motion/MotionInfo"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#class MotionInfo : public MotionRequest

MotionRequest motionRequest
bool isMotionStable   #/**< If true, the motion is stable, leading to a valid torso / camera matrix. */
Pose2D upcomingOdometryOffset   # /**< The remaining odometry offset for the currently executed motion. */
bool upcomingOdometryOffsetValid   # /**< Whether the \c upcomingOdometryOffset is precise enough to be used */


================================================================================
MSG: bh_motion/MotionRequest
# This expresses a Motion request.

uint8 motion  # /**< The selected motion. ENUM(Motion: walk, bike, specialAction, stand);*/

SpecialActionRequest specialActionRequest # /**< The special action request, if it is the selected motion. */
WalkRequest walkRequest  # /**< The walk request, if it is the selected motion. */
BikeRequest bikeRequest  # /**< The kick request, if it is the selected motion. */


================================================================================
MSG: bh_motion/SpecialActionRequest
# This expresses a special action requests.

# ENUM(SpecialActionID: playDead, standUpBackNao, standUpFrontNao, sitDown, sitDownKeeper, goUp, keeperJumpLeftSign);

uint8 specialAction  #; /**< The special action selected. */
bool mirror          #; /**< Mirror left and right. */


# FALTA getSpecialActionFromName

================================================================================
MSG: bh_motion/WalkRequest
# This expresses a walk request.


#(ENUM(Mode: speedMode, /**< Interpret \c speed as absolute walking speed and ignore \c target. */
#    percentageSpeedMode, /**< Interpret \c speed as percentage walking speed and ignore \c target. */
#    targetMode /**< Use \c target as walking target relative to the current position of the robot and interpret \c speed as percentage walking speed. */);)

uint32 mode  #/**< The walking mode. */
Pose2D speed #/**< Walking target, in mm and radians, relative to the robot. Use either a speed or a target. */
Pose2D target #/**< Walking target, in mm and radians, relative to the robot. Use either a speed or a target. */
bool pedantic #/**< Allows to disable the step size stabilization. set it when precision is indispensable. */
bool dribbling

uint32 kickType
Vector2 kickBallPosition
Vector2 kickTarget

================================================================================
MSG: bh_motion/Pose2D
# This expresses a position and orientation on a 2D (rotation, transaltion.x, transation.y).

float32 rotation
Translation translation

================================================================================
MSG: bh_motion/Translation
# This expresses an x, y translation

float32 x
float32 y

================================================================================
MSG: bh_motion/Vector2
float32 x 
float32 y


================================================================================
MSG: bh_motion/BikeRequest
bool mirror
bool dynamical
bool ballSpecial
uint8 bMotionType   # ENUM(BMotionID: kickForward, newKick, none)


DynPoint[2] dynPoints


================================================================================
MSG: bh_motion/DynPoint
uint32 limb
uint32 phaseNumber
uint32 duration
Vector3 translation
Vector3 angle
Vector3 odometryOffset

================================================================================
MSG: bh_motion/Vector3
float32 x 
float32 y
float32 z

"""
  __slots__ = ['motionRequest','isMotionStable','upcomingOdometryOffset','upcomingOdometryOffsetValid']
  _slot_types = ['bh_motion/MotionRequest','bool','bh_motion/Pose2D','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       motionRequest,isMotionStable,upcomingOdometryOffset,upcomingOdometryOffsetValid

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MotionInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.motionRequest is None:
        self.motionRequest = bh_motion.msg.MotionRequest()
      if self.isMotionStable is None:
        self.isMotionStable = False
      if self.upcomingOdometryOffset is None:
        self.upcomingOdometryOffset = bh_motion.msg.Pose2D()
      if self.upcomingOdometryOffsetValid is None:
        self.upcomingOdometryOffsetValid = False
    else:
      self.motionRequest = bh_motion.msg.MotionRequest()
      self.isMotionStable = False
      self.upcomingOdometryOffset = bh_motion.msg.Pose2D()
      self.upcomingOdometryOffsetValid = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3BI6f2BI4f4B.pack(_x.motionRequest.motion, _x.motionRequest.specialActionRequest.specialAction, _x.motionRequest.specialActionRequest.mirror, _x.motionRequest.walkRequest.mode, _x.motionRequest.walkRequest.speed.rotation, _x.motionRequest.walkRequest.speed.translation.x, _x.motionRequest.walkRequest.speed.translation.y, _x.motionRequest.walkRequest.target.rotation, _x.motionRequest.walkRequest.target.translation.x, _x.motionRequest.walkRequest.target.translation.y, _x.motionRequest.walkRequest.pedantic, _x.motionRequest.walkRequest.dribbling, _x.motionRequest.walkRequest.kickType, _x.motionRequest.walkRequest.kickBallPosition.x, _x.motionRequest.walkRequest.kickBallPosition.y, _x.motionRequest.walkRequest.kickTarget.x, _x.motionRequest.walkRequest.kickTarget.y, _x.motionRequest.bikeRequest.mirror, _x.motionRequest.bikeRequest.dynamical, _x.motionRequest.bikeRequest.ballSpecial, _x.motionRequest.bikeRequest.bMotionType))
      for val1 in self.motionRequest.bikeRequest.dynPoints:
        _x = val1
        buff.write(_struct_3I.pack(_x.limb, _x.phaseNumber, _x.duration))
        _v1 = val1.translation
        _x = _v1
        buff.write(_struct_3f.pack(_x.x, _x.y, _x.z))
        _v2 = val1.angle
        _x = _v2
        buff.write(_struct_3f.pack(_x.x, _x.y, _x.z))
        _v3 = val1.odometryOffset
        _x = _v3
        buff.write(_struct_3f.pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_struct_B3fB.pack(_x.isMotionStable, _x.upcomingOdometryOffset.rotation, _x.upcomingOdometryOffset.translation.x, _x.upcomingOdometryOffset.translation.y, _x.upcomingOdometryOffsetValid))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.motionRequest is None:
        self.motionRequest = bh_motion.msg.MotionRequest()
      if self.upcomingOdometryOffset is None:
        self.upcomingOdometryOffset = bh_motion.msg.Pose2D()
      end = 0
      _x = self
      start = end
      end += 57
      (_x.motionRequest.motion, _x.motionRequest.specialActionRequest.specialAction, _x.motionRequest.specialActionRequest.mirror, _x.motionRequest.walkRequest.mode, _x.motionRequest.walkRequest.speed.rotation, _x.motionRequest.walkRequest.speed.translation.x, _x.motionRequest.walkRequest.speed.translation.y, _x.motionRequest.walkRequest.target.rotation, _x.motionRequest.walkRequest.target.translation.x, _x.motionRequest.walkRequest.target.translation.y, _x.motionRequest.walkRequest.pedantic, _x.motionRequest.walkRequest.dribbling, _x.motionRequest.walkRequest.kickType, _x.motionRequest.walkRequest.kickBallPosition.x, _x.motionRequest.walkRequest.kickBallPosition.y, _x.motionRequest.walkRequest.kickTarget.x, _x.motionRequest.walkRequest.kickTarget.y, _x.motionRequest.bikeRequest.mirror, _x.motionRequest.bikeRequest.dynamical, _x.motionRequest.bikeRequest.ballSpecial, _x.motionRequest.bikeRequest.bMotionType,) = _struct_3BI6f2BI4f4B.unpack(str[start:end])
      self.motionRequest.specialActionRequest.mirror = bool(self.motionRequest.specialActionRequest.mirror)
      self.motionRequest.walkRequest.pedantic = bool(self.motionRequest.walkRequest.pedantic)
      self.motionRequest.walkRequest.dribbling = bool(self.motionRequest.walkRequest.dribbling)
      self.motionRequest.bikeRequest.mirror = bool(self.motionRequest.bikeRequest.mirror)
      self.motionRequest.bikeRequest.dynamical = bool(self.motionRequest.bikeRequest.dynamical)
      self.motionRequest.bikeRequest.ballSpecial = bool(self.motionRequest.bikeRequest.ballSpecial)
      self.motionRequest.bikeRequest.dynPoints = []
      for i in range(0, 2):
        val1 = bh_motion.msg.DynPoint()
        _x = val1
        start = end
        end += 12
        (_x.limb, _x.phaseNumber, _x.duration,) = _struct_3I.unpack(str[start:end])
        _v4 = val1.translation
        _x = _v4
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _struct_3f.unpack(str[start:end])
        _v5 = val1.angle
        _x = _v5
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _struct_3f.unpack(str[start:end])
        _v6 = val1.odometryOffset
        _x = _v6
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _struct_3f.unpack(str[start:end])
        self.motionRequest.bikeRequest.dynPoints.append(val1)
      _x = self
      start = end
      end += 14
      (_x.isMotionStable, _x.upcomingOdometryOffset.rotation, _x.upcomingOdometryOffset.translation.x, _x.upcomingOdometryOffset.translation.y, _x.upcomingOdometryOffsetValid,) = _struct_B3fB.unpack(str[start:end])
      self.isMotionStable = bool(self.isMotionStable)
      self.upcomingOdometryOffsetValid = bool(self.upcomingOdometryOffsetValid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3BI6f2BI4f4B.pack(_x.motionRequest.motion, _x.motionRequest.specialActionRequest.specialAction, _x.motionRequest.specialActionRequest.mirror, _x.motionRequest.walkRequest.mode, _x.motionRequest.walkRequest.speed.rotation, _x.motionRequest.walkRequest.speed.translation.x, _x.motionRequest.walkRequest.speed.translation.y, _x.motionRequest.walkRequest.target.rotation, _x.motionRequest.walkRequest.target.translation.x, _x.motionRequest.walkRequest.target.translation.y, _x.motionRequest.walkRequest.pedantic, _x.motionRequest.walkRequest.dribbling, _x.motionRequest.walkRequest.kickType, _x.motionRequest.walkRequest.kickBallPosition.x, _x.motionRequest.walkRequest.kickBallPosition.y, _x.motionRequest.walkRequest.kickTarget.x, _x.motionRequest.walkRequest.kickTarget.y, _x.motionRequest.bikeRequest.mirror, _x.motionRequest.bikeRequest.dynamical, _x.motionRequest.bikeRequest.ballSpecial, _x.motionRequest.bikeRequest.bMotionType))
      for val1 in self.motionRequest.bikeRequest.dynPoints:
        _x = val1
        buff.write(_struct_3I.pack(_x.limb, _x.phaseNumber, _x.duration))
        _v7 = val1.translation
        _x = _v7
        buff.write(_struct_3f.pack(_x.x, _x.y, _x.z))
        _v8 = val1.angle
        _x = _v8
        buff.write(_struct_3f.pack(_x.x, _x.y, _x.z))
        _v9 = val1.odometryOffset
        _x = _v9
        buff.write(_struct_3f.pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_struct_B3fB.pack(_x.isMotionStable, _x.upcomingOdometryOffset.rotation, _x.upcomingOdometryOffset.translation.x, _x.upcomingOdometryOffset.translation.y, _x.upcomingOdometryOffsetValid))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.motionRequest is None:
        self.motionRequest = bh_motion.msg.MotionRequest()
      if self.upcomingOdometryOffset is None:
        self.upcomingOdometryOffset = bh_motion.msg.Pose2D()
      end = 0
      _x = self
      start = end
      end += 57
      (_x.motionRequest.motion, _x.motionRequest.specialActionRequest.specialAction, _x.motionRequest.specialActionRequest.mirror, _x.motionRequest.walkRequest.mode, _x.motionRequest.walkRequest.speed.rotation, _x.motionRequest.walkRequest.speed.translation.x, _x.motionRequest.walkRequest.speed.translation.y, _x.motionRequest.walkRequest.target.rotation, _x.motionRequest.walkRequest.target.translation.x, _x.motionRequest.walkRequest.target.translation.y, _x.motionRequest.walkRequest.pedantic, _x.motionRequest.walkRequest.dribbling, _x.motionRequest.walkRequest.kickType, _x.motionRequest.walkRequest.kickBallPosition.x, _x.motionRequest.walkRequest.kickBallPosition.y, _x.motionRequest.walkRequest.kickTarget.x, _x.motionRequest.walkRequest.kickTarget.y, _x.motionRequest.bikeRequest.mirror, _x.motionRequest.bikeRequest.dynamical, _x.motionRequest.bikeRequest.ballSpecial, _x.motionRequest.bikeRequest.bMotionType,) = _struct_3BI6f2BI4f4B.unpack(str[start:end])
      self.motionRequest.specialActionRequest.mirror = bool(self.motionRequest.specialActionRequest.mirror)
      self.motionRequest.walkRequest.pedantic = bool(self.motionRequest.walkRequest.pedantic)
      self.motionRequest.walkRequest.dribbling = bool(self.motionRequest.walkRequest.dribbling)
      self.motionRequest.bikeRequest.mirror = bool(self.motionRequest.bikeRequest.mirror)
      self.motionRequest.bikeRequest.dynamical = bool(self.motionRequest.bikeRequest.dynamical)
      self.motionRequest.bikeRequest.ballSpecial = bool(self.motionRequest.bikeRequest.ballSpecial)
      self.motionRequest.bikeRequest.dynPoints = []
      for i in range(0, 2):
        val1 = bh_motion.msg.DynPoint()
        _x = val1
        start = end
        end += 12
        (_x.limb, _x.phaseNumber, _x.duration,) = _struct_3I.unpack(str[start:end])
        _v10 = val1.translation
        _x = _v10
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _struct_3f.unpack(str[start:end])
        _v11 = val1.angle
        _x = _v11
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _struct_3f.unpack(str[start:end])
        _v12 = val1.odometryOffset
        _x = _v12
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _struct_3f.unpack(str[start:end])
        self.motionRequest.bikeRequest.dynPoints.append(val1)
      _x = self
      start = end
      end += 14
      (_x.isMotionStable, _x.upcomingOdometryOffset.rotation, _x.upcomingOdometryOffset.translation.x, _x.upcomingOdometryOffset.translation.y, _x.upcomingOdometryOffsetValid,) = _struct_B3fB.unpack(str[start:end])
      self.isMotionStable = bool(self.isMotionStable)
      self.upcomingOdometryOffsetValid = bool(self.upcomingOdometryOffsetValid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3BI6f2BI4f4B = struct.Struct("<3BI6f2BI4f4B")
_struct_3I = struct.Struct("<3I")
_struct_3f = struct.Struct("<3f")
_struct_B3fB = struct.Struct("<B3fB")
