"""autogenerated by genpy from bh_motion/OdometryData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import bh_motion.msg

class OdometryData(genpy.Message):
  _md5sum = "fc1c837775757ead2cbd5a0f0fa12f17"
  _type = "bh_motion/OdometryData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Pose2D pose2D

================================================================================
MSG: bh_motion/Pose2D
# This expresses a position and orientation on a 2D (rotation, transaltion.x, transation.y).

float32 rotation
Translation translation

================================================================================
MSG: bh_motion/Translation
# This expresses an x, y translation

float32 x
float32 y

"""
  __slots__ = ['pose2D']
  _slot_types = ['bh_motion/Pose2D']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pose2D

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OdometryData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pose2D is None:
        self.pose2D = bh_motion.msg.Pose2D()
    else:
      self.pose2D = bh_motion.msg.Pose2D()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3f.pack(_x.pose2D.rotation, _x.pose2D.translation.x, _x.pose2D.translation.y))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pose2D is None:
        self.pose2D = bh_motion.msg.Pose2D()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.pose2D.rotation, _x.pose2D.translation.x, _x.pose2D.translation.y,) = _struct_3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3f.pack(_x.pose2D.rotation, _x.pose2D.translation.x, _x.pose2D.translation.y))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pose2D is None:
        self.pose2D = bh_motion.msg.Pose2D()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.pose2D.rotation, _x.pose2D.translation.x, _x.pose2D.translation.y,) = _struct_3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3f = struct.Struct("<3f")
