"""autogenerated by genpy from bh_motion/SpecialActionRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SpecialActionRequest(genpy.Message):
  _md5sum = "898ecd392883915857a1dcaaef2c3cb0"
  _type = "bh_motion/SpecialActionRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# This expresses a special action requests.

# ENUM(SpecialActionID: playDead, standUpBackNao, standUpFrontNao, sitDown, sitDownKeeper, goUp, keeperJumpLeftSign);

uint8 specialAction  #; /**< The special action selected. */
bool mirror          #; /**< Mirror left and right. */


# FALTA getSpecialActionFromName

"""
  __slots__ = ['specialAction','mirror']
  _slot_types = ['uint8','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       specialAction,mirror

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SpecialActionRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.specialAction is None:
        self.specialAction = 0
      if self.mirror is None:
        self.mirror = False
    else:
      self.specialAction = 0
      self.mirror = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2B.pack(_x.specialAction, _x.mirror))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.specialAction, _x.mirror,) = _struct_2B.unpack(str[start:end])
      self.mirror = bool(self.mirror)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2B.pack(_x.specialAction, _x.mirror))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.specialAction, _x.mirror,) = _struct_2B.unpack(str[start:end])
      self.mirror = bool(self.mirror)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2B = struct.Struct("<2B")
